### ISSUE TITLE
Testing and my view points

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer#16]
Okey guys, some points. Inspiration https://github.com/jstransformers/jstransformer-liquor/pull/1 and [tests like that](https://github.com/jstransformers/jstransformer-jazz/blob/master/test/index.js)

Please, lets come to that to use `jstransformer` for all the modules. It will be just in devDeps, so I dont see the problem.

Current testing flow is awful for me. Tests should be descriptive, should be as an examples, should test some more real use-cases (I mean, more than just `hello {{name}}`) or template engine specifics, also should have descriptive descriptions. 
Tests should be [like these](https://github.com/jstransformers/jstransformer-coffeekup/blob/master/test/index.js). 

What is that "Mote.js" description (mentioning [jstransformer-mote test](https://github.com/jstransformers/jstransformer-mote/blob/master/test/index.js#L19))? - Nothing. 
You even [set `transform.name` as test description](https://github.com/jstransformers/generator-jstransformer/blob/master/app/templates/test/index.js#L20) in our generator.

Using `testit` for just one simple line saying "mote.js" or "liquor" to the stdout, whaa?!

Tests [like this](https://github.com/jstransformers/jstransformer-jazz/blob/master/test/index.js) dont have meaning for me. They told me nothing, what remains to users?

I also dont like very much `assert.equal`, so [`assertit`.equal is assert's `strictEqual`](https://github.com/tunnckoCore/assertit/blob/master/index.js#L54)

[assertit](https://github.com/tunnckoCore/assertit) is enhancement, thin layer on top of `testit` and `assert` - *read* [it's tests](https://github.com/tunnckoCore/assertit/blob/master/test.js) to see the actual usage.

**Comment by TimothyGu** [comment]
> Please, lets come to that to use `jstransformer` for all the modules. It will be just in devDeps, so I dont see the problem.

I don't have an opinion on this.

> Current testing flow is awful for me. Tests should be descriptive, should be as an examples, should test some more real use-cases (I mean, more than just `hello {{name}}`) or template engine specifics, also should have descriptive descriptions.
Tests should be [like these](https://github.com/jstransformers/jstransformer-coffeekup/blob/master/test/index.js). 

This isn't the test suite for the engine. We want to make sure our *wrapper* works. I don't see how the description can be more descriptive than that.

> Using `testit` for just one simple line saying "mote.js" or "liquor" to the stdout, whaa?!

Again, no opinion on this, although I do think testit makes it easier to add new tests while preserving the prettiness.

> Tests [like this](https://github.com/jstransformers/jstransformer-jazz/blob/master/test/index.js) dont have meaning for me. They told me nothing, what remains to users?

They tell you that this module works. If you want to know how to use this module, then you should look at the documentation for jstransformer instead.

> I also dont like very much `assert.equal`, so [`assertit`.equal is assert's `strictEqual`](https://github.com/tunnckoCore/assertit/blob/master/index.js#L54)
>
> [assertit](https://github.com/tunnckoCore/assertit) is enhancement, thin layer on top of `testit` and `assert` - *read* [it's tests](https://github.com/tunnckoCore/assertit/blob/master/test.js) to see the actual usage.

A SEPARATE MODULE FOR ONE ASSERT???? WHAAAAA?!

testit actually offers some improvements: colors and check marks. I really don't see the point in using assertit.

**Comment by tunnckoCore** [comment]
> testit actually offers some improvements: colors and check marks. I really don't see the point in using assertit.

syntax sugar for me, and maybe not only me. For me its enough just to use assert.strictEqual and testit, but 1) I want to write lower letters in row and 2) sometime I need correct and strict type asserts so .. yea, it have point of existence.

> testit actually offers some improvements: colors and check marks

and whats the matter when you write just 4-6 letters?

> then you should look at the documentation for jstransformer instead.

omg, if we move with this logic, why you write "usage" example, better write readme like this

# jstransformer-foo
> go read our cool [jstransformer] documentation in our cool site. period.

??

**Comment by tunnckoCore** [comment]
> A SEPARATE MODULE FOR ONE ASSERT???? WHAAAAA?!

We can say this for **every** package in the node land.
Whole `mocha` or `tape` or `lab` or etc, for thing that can be done in 40-70 lines with default spec-like reporter?

**Comment by tunnckoCore** [comment]
> If you want to know how to use this module, then you should look at the documentation for jstransformer instead.

Its needless work and clicks and digging. Things should be intuitive.

**Comment by ForbesLindesay** [comment]
Lets try and keep this a reasoned debate as much as possible.  I'll try and address each of your points individually.

> We should use jstransformer in the tests

I have no strong opinion here.  I think it tends to lead to simpler tests if you don't use `jstransformer`.  It ultimately comes down to the difference between integration tests and unit tests.  Personally, I don't think it's that valuable to automate testing that jstransformer correctly normalises our module API.  I prefer instead to test that the module itself returns precisely what I expected it to return.

I don't mind too much if there is some variation on this point between modules.

The second thing you are suggesting is that even if a transformer just implements `compile` we should add tests for compile, compileFile, render, renderFile etc.  The problem with this is that it makes your test suite explode in size.  Check out the code coverage for jstransformer (https://github.com/jstransformers/jstransformer/tree/master/test) which is only about 75% complete.  If you plan to cover the full API surface in every module, you will end up with thousands of lines of test code per jstransformer.  This is why it's essential that we write **unit tests** for jstransformer.  We can always build some kind of higher level integration testing platform later, but right now it's not a priority because it's not catching a mistake that's actually common in practice.

> Tests should have descriptive names

In general, I agree with you.  On the other hand, our entire modules are about 30 lines long, and our test suites are usually less than 40 lines long.  With this in mind, it is of relatively little importance what we name our tests, because it's easy enough to just read the test and see what it's doing.  If a test is confusing, ask the author for clarification and then see if you can come up with a more descriptive name, otherwise just get on with life.

> Why use testit for just one simple line of output

Personally I have no strong opinion about whether testit is worth it for such simple tests.  I have many modules where I don't bother and just write the asserts directly and then put `console.log('tests passed')` at the end.  If testit seems overkill to you, don't bother with it.

If the complaint here is that we should have more tests/longer tests, I strongly disagree.  Tests should be just long enough to check that the code is all working correctly.  Every test has to be maintained, just like all other code.  Every time a new person wants to contribute a fix to one of our modules, they also have to fix the corresponding tests.  Having less testing code makes that easier.  It's important to strike the right balance.

> Some tests don't tell me anything.

Tests aren't meant to tell you how to use the module, they're meant to check the module functions correctly.  The test you link to does an excellent job of that.

> We should use assertit

Keep in mind that every module you use is something extra that people have to learn in order to contribute to your code base.  I have found very few occasions where `assert.strictEqual` and `assert.deepEqual` aren't sufficient for my requirements.  I encourage you to keep working on your own ideas around cleaner APIs and syntax sugar for tests, but for jstransformers I would prefer to use 6 extra characters for each assert in exchange for one fewer dependency, and one fewer layers of abstraction for people to unpick.


I hope that clears up a few things around why we are doing things the way we are doing them.  Feel free to ask further questions if there's anything that you don't understand.

**Comment by tunnckoCore** [comment]
> If you plan to cover the full API surface in every module, you will end up with thousands of lines of test code per jstransformer.

thousands no, but yea, you have right.

> Every time a new person wants to contribute a fix to one of our modules, they also have to fix the corresponding tests. Having less testing code makes that easier. It's important to strike the right balance.

:+1: 

> We should use assertit

Want to mention that I didn't said it.

***
Okey, I understand. But I'll stay with my current tests in my libs, using jstransformer, please dont be strict. Its supposed that I'll follow and maintain them the most.

If there's no more comments and thoughts we can close this :)
