### ISSUE TITLE
pixie

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer#182]
https://github.com/jamen/pixie

@jamen looks cool. Maybe inspired by tagged templates, haha? Good job.

**Comment by jamen** [comment]
Hey! Thanks.  

A lot of my projects are just little tests and experiments so I can learn more.  I created this one because I wanted a tiny templating engine (< 100 LOC there) that runs client side as well for another project I was doing.  Decided I would make it a standalone thing.

For small templates (e.g. formatting string) you want to template, it should be faster than most options.

But, It's not designed very scalable unfortunately.  Something like handlebars would be better as the template gets bigger and bigger (you can see some benchmarks I made in the repo).  However, I'm open to ideas and PRs.

**Comment by jamen** [comment]
Oh I forgot, one of the bigger aspects I like about pixie though is the array piece.

You can _preparse_ templates into arrays, pass them off to other functions for manipulation, and reuse them.  Feels more useful than the typical `render(template)(locals)` with no interpolation.

**Comment by jamen** [comment]
Thanks for reminding me btw!  I'm going to revisit and change some things now.

**Comment by tunnckoCore** [comment]
> You can preparse templates into arrays, pass them off to other functions for manipulation, and reuse them, or serialize as JSON.

Yea looks interesting. I also have few template engines in my account that are small - one is the 140bytes implementation by Jed Schmidt, another is by AbsurdJS, and the third is using tagged templates - gana/gana-compile. Actually started updating `es6-template` to v2 using gana and gana-compile, but another more important thing popuped and they are uncomplete now.

**Comment by jamen** [comment]
Awesome!  `es6-template` reminds me of a fun little thing I did called [`lazy-template`](https://github.com/jamen/lazy-template) (which is made on top of `pixie`).  Although it's less useful because it uses actual template literals.

**Comment by RobLoach** [comment]
https://github.com/jstransformers/jstransformer-pixie :+1: .... Pretty neat. Could add some Engine supports in the options array there too.
