### ISSUE TITLE
More flexible fallbacks

### ISSUE THREAD

**Issue by TimothyGu** [jstransformers/jstransformer#2]
For example currently compileFileAsync does this:

1. check and use compileFileAsync
2. check and use compileFile, which must use sync readFile
3. check and use compileAsync, wrapping it around async readFile
4. check and use compile, wrapping it around async readFile

Say I supply a synchronous compileFile, compileFileAsync is basically forced to use synchronous file IO, which might be suboptimal.

I propose a `compileFileCommon` function that handles the stuff common to both functions when `compile` is synchronous, and jstransformer automatically adding the file I/O operations.

Same goes for `compileClient` and `compileClientAsync`.

**Comment by TimothyGu** [comment]
![jstransformer](https://cloud.githubusercontent.com/assets/1538624/6162034/23b4ba04-b230-11e4-9be1-884a4f708897.png)

**Comment by ForbesLindesay** [comment]
I really want to focus on simplicity for jstransformer.  I went down the one method does everything route in Transformers and one of the problems I found was that some transformers can't really be given a string as a starting point.  e.g. browserify takes a file name (or names) and it really doesn't make sense to  give it a string.  This meant that we were wasting time on file IO by reading the files.

If the transformer could be async when called via `compileFileCommon` it should be able to implement `compileFileAsync` fairly trivially, so that should be used.  In addition, most `compileFile`/`compileFileAsync` methods will end up reading other files anyway (e.g. jade includes) and these would end up having to be synchronous in your example, so not much is gained by making just the initial read asynchronous.

**Comment by TimothyGu** [comment]
> I really want to focus on simplicity for jstransformer.  I went down the one method does everything route in Transformers and one of the problems I found was that some transformers can't really be given a string as a starting point.  e.g. browserify takes a file name (or names) and it really doesn't make sense to  give it a string.

Makes sense.

> If the transformer could be async when called via `compileFileCommon` it should be able to implement `compileFileAsync` fairly trivially, so that should be used. 

Not really. I don't want to deal with all those Promise stuff in my own transformer rather than in jstransformer, when I simply want to use readFile instead of readFileSync.

> In addition, most `compileFile`/`compileFileAsync` methods will end up reading other files anyway (e.g. jade includes) and these would end up having to be synchronous in your example, so not much is gained by making just the initial read asynchronous.

True.

**Comment by ForbesLindesay** [comment]
I think now that ES6 is coming out and we're getting Promises as part of the platform, we should be accepting that transforms that do asynchronous work should return Promises.  In the interest of simplicity, lets stick to the current API.

**Comment by TimothyGu** [comment]
Fair enough, not that I like promises.
