### ISSUE TITLE
Streams?

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#20]
![Streams](http://i.imgur.com/gPIz2U7.jpg)

I see lots of use of strings, but haven't seen much implementation surrounding [Streams](https://nodejs.org/api/stream.html). Any thoughts?

**Comment by ForbesLindesay** [comment]
I think streams are out of scope for core jstransformers:

1. Hardly any of the underlying libraries actually support streams (pretty much just browserify).
2. Streaming APIs are not particularly stable yet as none of the browsers implement anything yet.
3. Adding node.js style streams would make the bundle size explode for anyone hoping to browserify jstransformers.

It is needed for the CLI because we should definitely support piping (i.e. `cat foo.jade | jstransformer render jade > output.html`) but I think we should do that by just buffering all of stdin and writing everything to stdout in one go.

**Comment by RobLoach** [comment]
https://nodejs.org/api/stream.html#stream_class_stream_transform
