### ISSUE TITLE
`outputFormat` of some template engines

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer#8]
@ForbesLindesay @RobLoach i think it should be `text` not exactly `html` as now in `mustache` transformer

**Comment by ForbesLindesay** [comment]
The way to think of output format is as the answer to the question "what should I use as the default file extension for the output of the user failed to specify one". 90% of the time, template engines are used to generate html, so default to html.  Other times it might be xml or plain text, in those cases the user would have to specify that.

Another way to look at this is that the property is only worth having at all if it is somehow useful.  Currently all our transformers return text, so that's not a very useful thing to tell the consumer, but it may be useful to say " this transformer usually produces html"

**Comment by tunnckoCore** [comment]
Very clear, thanks.
